# Netlify deployment configuration
[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://your-backend-url.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.onrender.com/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200